<img src="{{ asset('images/about1.jpg') }}" alt="Пример изображения">
<img src="{{ asset('images/about2.jpg') }}" alt="Пример изображения">
<img src="{{ asset('images/afisha_preview.png') }}" alt="Пример изображения">
<img src="{{ asset('images/empty_profile_avatar.png') }}" alt="Пример изображения">
<img src="{{ asset('images/excurs1.webp') }}" alt="Пример изображения">
<img src="{{ asset('images/excurs2.webp') }}" alt="Пример изображения">
<img src="{{ asset('images/excurs3.webp') }}" alt="Пример изображения">
<img src="{{ asset('images/exhibition1.jpg') }}" alt="Пример изображения">
<img src="{{ asset('images/exhibition2.jpg') }}" alt="Пример изображения">
<img src="{{ asset('images/exhibition3.jpg') }}" alt="Пример изображения">
<img src="{{ asset('images/food1.jpg') }}" alt="Пример изображения">
<img src="{{ asset('images/food2.jpg') }}" alt="Пример изображения">
<img src="{{ asset('images/food3.jpg') }}" alt="Пример изображения">
<img src="{{ asset('images/food_map.png') }}" alt="Пример изображения">
<img src="{{ asset('images/food_place_holder.jpg') }}" alt="Пример изображения">
<img src="{{ asset('images/home_image.png') }}" alt="Пример изображения">
<img src="{{ asset('images/logo.png') }}" alt="Пример изображения">
<img src="{{ asset('images/nature.png') }}" alt="Пример изображения">
<img src="{{ asset('images/news_image.png') }}" alt="Пример изображения">
<img src="{{ asset('images/no-image.jpg') }}" alt="Пример изображения">
<img src="{{ asset('images/orig.jpeg') }}" alt="Пример изображения">
<img src="{{ asset('images/places_preview.png') }}" alt="Пример изображения">
<img src="{{ asset('images/point.png') }}" alt="Пример изображения">
<img src="{{ asset('images/poster1.png') }}" alt="Пример изображения">
<img src="{{ asset('images/poster2.webp') }}" alt="Пример изображения">
<img src="{{ asset('images/poster3.jpg') }}" alt="Пример изображения">
<img src="{{ asset('images/posterbah1.jpg') }}" alt="Пример изображения">
<img src="{{ asset('images/restaurant.png') }}" alt="Пример изображения">
<img src="{{ asset('images/restaurant_preview.png') }}" alt="Пример изображения">
<img src="{{ asset('images/review1.jpg') }}" alt="Пример изображения">
<img src="{{ asset('images/review2.jpg') }}" alt="Пример изображения">
<img src="{{ asset('images/review3.jpg') }}" alt="Пример изображения">
<img src="{{ asset('images/rew_post1.jpeg') }}" alt="Пример изображения">
<img src="{{ asset('images/rew_post2.jpg') }}" alt="Пример изображения">
<img src="{{ asset('images/routes.png') }}" alt="Пример изображения">
<img src="{{ asset('images/routes_place_holder.jpg') }}" alt="Пример изображения">
<img src="{{ asset('images/sale_example.png') }}" alt="Пример изображения">
<img src="{{ asset('images/shopping_place_holder.jpg') }}" alt="Пример изображения">
<img src="{{ asset('images/shopping_preview.png') }}" alt="Пример изображения">
<img src="{{ asset('images/show1.jpg') }}" alt="Пример изображения">
<img src="{{ asset('images/show2.jpg') }}" alt="Пример изображения">
<img src="{{ asset('images/show3.jpg') }}" alt="Пример изображения">
<img src="{{ asset('images/sights_places.png') }}" alt="Пример изображения">
<img src="{{ asset('images/sights_place_holder.jpg') }}" alt="Пример изображения">
<img src="{{ asset('images/sights_preview.png') }}" alt="Пример изображения">
<img src="{{ asset('images/welcome.png') }}" alt="Пример изображения">



